# Generated by Django 3.2.18 on 2023-02-18 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sync_youtube', '0002_auto_20230218_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubesong',
            name='local_playlist',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='songs', to='sync_youtube.localplaylist'),
        ),
        migrations.AlterField(
            model_name='youtubesong',
            name='remote_playlist',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='songs', to='sync_youtube.remoteplaylist'),
        ),
    ]
