# Generated by Django 3.2.18 on 2023-02-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_youtube', '0003_auto_20230218_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='localplaylist',
            name='should_update',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='youtubesong',
            name='should_not_exist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='youtubesong',
            name='third_party_playlist_item_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
