# Generated by Django 3.2.18 on 2023-03-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_youtube', '0004_auto_20230225_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubesong',
            name='should_not_be_published',
            field=models.BooleanField(default=False),
        ),
    ]
